[pytest]
# Add command line arguments by default
addopts = -v -s -n 3 --reruns 1 --html=reports/report.html --self-contained-html --capture=no

# Define where the test files are
testpaths = stepDefinitions
python_files = test_*.py
python_classes = Test*
python_functions = test_*

pythonpath = .


# Custom markers to categorize tests (like @Smoke in Cucumber)
markers =
    smoke: vital functional tests
    regression: full system check
    api: tests for API endpoints
